//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axis.Share.Soap.ActionService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionTemplateNotFoundFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionParameter
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionParameters
    {
        
        private ActionParameter[] parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter", Order=0)]
        public ActionParameter[] Parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class NewActionConfiguration
    {
        
        private string nameField;
        
        private string templateTokenField;
        
        private ActionParameters parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TemplateToken
        {
            get
            {
                return this.templateTokenField;
            }
            set
            {
                this.templateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ActionParameters Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionTemplateParameter
    {
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionTemplate
    {
        
        private string templateTokenField;
        
        private string recipientTemplateField;
        
        private ActionTemplateParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TemplateToken
        {
            get
            {
                return this.templateTokenField;
            }
            set
            {
                this.templateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RecipientTemplate
        {
            get
            {
                return this.recipientTemplateField;
            }
            set
            {
                this.recipientTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public ActionTemplateParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ParametersMissmatchFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class InvalidActionConfigurationFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionConfigurationNotFoundFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionConfigurationIsInUseFault
    {
        
        private UsedActionRule[] usedByActionRulesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ActionRule", IsNullable=false)]
        public UsedActionRule[] UsedByActionRules
        {
            get
            {
                return this.usedByActionRulesField;
            }
            set
            {
                this.usedByActionRulesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class UsedActionRule
    {
        
        private string actionRuleIDField;
        
        private string actionRuleNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string ActionRuleID
        {
            get
            {
                return this.actionRuleIDField;
            }
            set
            {
                this.actionRuleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ActionRuleName
        {
            get
            {
                return this.actionRuleNameField;
            }
            set
            {
                this.actionRuleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class RecipientTemplateNotFoundFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class RecipientConfigurationNotFoundFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class InvalidConditionFilterFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class InsufficientActivationRuleFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class InvalidActivationTimeoutFault
    {
        
        private string maximumTimeoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=0)]
        public string MaximumTimeout
        {
            get
            {
                return this.maximumTimeoutField;
            }
            set
            {
                this.maximumTimeoutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class InvalidFilterFaultType : BaseFaultType
    {
        
        private System.Xml.XmlQualifiedName[] unknownFilterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnknownFilter", Order=0)]
        public System.Xml.XmlQualifiedName[] UnknownFilter
        {
            get
            {
                return this.unknownFilterField;
            }
            set
            {
                this.unknownFilterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResumeFailedFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PauseFailedFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnableToDestroySubscriptionFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnacceptableTerminationTimeFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnableToCreatePullPointFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnableToDestroyPullPointFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnableToGetMessagesFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NoCurrentMessageOnTopicFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnacceptableInitialTerminationTimeFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NotifyMessageNotSupportedFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnsupportedPolicyRequestFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UnrecognizedPolicyRequestFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidMessageContentExpressionFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidProducerPropertiesExpressionFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipleTopicsSpecifiedFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopicNotSupportedFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidTopicExpressionFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopicExpressionDialectUnknownFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidFilterFaultType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubscribeCreationFailedFaultType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsrf/bf-2")]
    public partial class BaseFaultType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.DateTime timestampField;
        
        private EndpointReferenceType originatorField;
        
        private BaseFaultTypeErrorCode errorCodeField;
        
        private BaseFaultTypeDescription[] descriptionField;
        
        private System.Xml.XmlElement faultCauseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public EndpointReferenceType Originator
        {
            get
            {
                return this.originatorField;
            }
            set
            {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public BaseFaultTypeErrorCode ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Order=4)]
        public BaseFaultTypeDescription[] Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Xml.XmlElement FaultCause
        {
            get
            {
                return this.faultCauseField;
            }
            set
            {
                this.faultCauseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class EndpointReferenceType
    {
        
        private AttributedURIType addressField;
        
        private ReferenceParametersType referenceParametersField;
        
        private MetadataType metadataField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedURIType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReferenceParametersType ReferenceParameters
        {
            get
            {
                return this.referenceParametersField;
            }
            set
            {
                this.referenceParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MetadataType Metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class MetadataType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wsrf/bf-2")]
    public partial class BaseFaultTypeErrorCode
    {
        
        private string dialectField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string dialect
        {
            get
            {
                return this.dialectField;
            }
            set
            {
                this.dialectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wsrf/bf-2")]
    public partial class BaseFaultTypeDescription
    {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang
        {
            get
            {
                return this.langField;
            }
            set
            {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class ResumeFailedFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class PauseFailedFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnableToDestroySubscriptionFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnacceptableTerminationTimeFaultType : BaseFaultType
    {
        
        private System.DateTime minimumTimeField;
        
        private System.DateTime maximumTimeField;
        
        private bool maximumTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime MinimumTime
        {
            get
            {
                return this.minimumTimeField;
            }
            set
            {
                this.minimumTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime MaximumTime
        {
            get
            {
                return this.maximumTimeField;
            }
            set
            {
                this.maximumTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumTimeSpecified
        {
            get
            {
                return this.maximumTimeFieldSpecified;
            }
            set
            {
                this.maximumTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnableToCreatePullPointFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnableToDestroyPullPointFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnableToGetMessagesFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class NoCurrentMessageOnTopicFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnacceptableInitialTerminationTimeFaultType : BaseFaultType
    {
        
        private System.DateTime minimumTimeField;
        
        private System.DateTime maximumTimeField;
        
        private bool maximumTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime MinimumTime
        {
            get
            {
                return this.minimumTimeField;
            }
            set
            {
                this.minimumTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime MaximumTime
        {
            get
            {
                return this.maximumTimeField;
            }
            set
            {
                this.maximumTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumTimeSpecified
        {
            get
            {
                return this.maximumTimeFieldSpecified;
            }
            set
            {
                this.maximumTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class NotifyMessageNotSupportedFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnsupportedPolicyRequestFaultType : BaseFaultType
    {
        
        private System.Xml.XmlQualifiedName[] unsupportedPolicyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnsupportedPolicy", Order=0)]
        public System.Xml.XmlQualifiedName[] UnsupportedPolicy
        {
            get
            {
                return this.unsupportedPolicyField;
            }
            set
            {
                this.unsupportedPolicyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class UnrecognizedPolicyRequestFaultType : BaseFaultType
    {
        
        private System.Xml.XmlQualifiedName[] unrecognizedPolicyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnrecognizedPolicy", Order=0)]
        public System.Xml.XmlQualifiedName[] UnrecognizedPolicy
        {
            get
            {
                return this.unrecognizedPolicyField;
            }
            set
            {
                this.unrecognizedPolicyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class InvalidMessageContentExpressionFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class InvalidProducerPropertiesExpressionFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class MultipleTopicsSpecifiedFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class TopicNotSupportedFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class InvalidTopicExpressionFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class TopicExpressionDialectUnknownFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class SubscribeCreationFailedFaultType : BaseFaultType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionRuleNotFoundFault
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.axis.com/vapix/ws/action1", ConfigurationName="Axis.Share.Soap.ActionService.Action")]
    public interface Action
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/GetActionTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionTemplatesResponse> GetActionTemplatesAsync(Axis.Share.Soap.ActionService.GetActionTemplatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/AddActionConfiguration", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ActionTemplateNotFoundFault), Action="http://www.axis.com/vapix/ws/action1/AddActionConfiguration", Name="ActionTemplateNotFoundFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ParametersMissmatchFault), Action="http://www.axis.com/vapix/ws/action1/AddActionConfiguration", Name="ParametersMissmatchFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InvalidActionConfigurationFault), Action="http://www.axis.com/vapix/ws/action1/AddActionConfiguration", Name="InvalidActionConfigurationFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddActionConfigurationResponse> AddActionConfigurationAsync(Axis.Share.Soap.ActionService.AddActionConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/RemoveActionConfiguration", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ActionConfigurationNotFoundFault), Action="http://www.axis.com/vapix/ws/action1/RemoveActionConfiguration", Name="ActionConfigurationNotFoundFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ActionConfigurationIsInUseFault), Action="http://www.axis.com/vapix/ws/action1/RemoveActionConfiguration", Name="ActionConfigurationIsInUseFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveActionConfigurationResponse> RemoveActionConfigurationAsync(Axis.Share.Soap.ActionService.RemoveActionConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/GetActionConfigurations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionConfigurationsResponse> GetActionConfigurationsAsync(Axis.Share.Soap.ActionService.GetActionConfigurationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/GetRecipientTemplates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetRecipientTemplatesResponse> GetRecipientTemplatesAsync(Axis.Share.Soap.ActionService.GetRecipientTemplatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/AddRecipientConfiguration", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.RecipientTemplateNotFoundFault), Action="http://www.axis.com/vapix/ws/action1/AddRecipientConfiguration", Name="RecipientTemplateNotFoundFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ParametersMissmatchFault), Action="http://www.axis.com/vapix/ws/action1/AddRecipientConfiguration", Name="ParametersMissmatchFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddRecipientConfigurationResponse> AddRecipientConfigurationAsync(Axis.Share.Soap.ActionService.AddRecipientConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/RemoveRecipientConfiguration", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.RecipientConfigurationNotFoundFault), Action="http://www.axis.com/vapix/ws/action1/RemoveRecipientConfiguration", Name="RecipientConfigurationNotFoundFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveRecipientConfigurationResponse> RemoveRecipientConfigurationAsync(Axis.Share.Soap.ActionService.RemoveRecipientConfigurationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/GetRecipientConfigurations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetRecipientConfigurationsResponse> GetRecipientConfigurationsAsync(Axis.Share.Soap.ActionService.GetRecipientConfigurationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/AddActionRule", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InvalidConditionFilterFault), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="InvalidConditionFilterFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ActionConfigurationNotFoundFault), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="ActionConfigurationNotFoundFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InsufficientActivationRuleFault), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="InsufficientActivationRuleFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InvalidActivationTimeoutFault), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="InvalidActivationTimeoutFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InvalidFilterFaultType), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="InvalidFilterFault", Namespace="http://docs.oasis-open.org/wsn/b-2")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.TopicExpressionDialectUnknownFaultType), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="TopicExpressionDialectUnknownFault", Namespace="http://docs.oasis-open.org/wsn/b-2")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InvalidTopicExpressionFaultType), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="InvalidTopicExpressionFault", Namespace="http://docs.oasis-open.org/wsn/b-2")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.InvalidMessageContentExpressionFaultType), Action="http://www.axis.com/vapix/ws/action1/AddActionRule", Name="InvalidMessageContentExpressionFault", Namespace="http://docs.oasis-open.org/wsn/b-2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddActionRuleResponse> AddActionRuleAsync(Axis.Share.Soap.ActionService.AddActionRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/GetActionRules", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionRulesResponse> GetActionRulesAsync(Axis.Share.Soap.ActionService.GetActionRulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/action1/RemoveActionRule", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.ActionService.ActionRuleNotFoundFault), Action="http://www.axis.com/vapix/ws/action1/RemoveActionRule", Name="ActionRuleNotFoundFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveActionRuleResponse> RemoveActionRuleAsync(Axis.Share.Soap.ActionService.RemoveActionRuleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionTemplates", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetActionTemplatesRequest
    {
        
        public GetActionTemplatesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionTemplatesResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetActionTemplatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Axis.Share.Soap.ActionService.ActionTemplate[] ActionTemplates;
        
        public GetActionTemplatesResponse()
        {
        }
        
        public GetActionTemplatesResponse(Axis.Share.Soap.ActionService.ActionTemplate[] ActionTemplates)
        {
            this.ActionTemplates = ActionTemplates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActionConfiguration", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class AddActionConfigurationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        public Axis.Share.Soap.ActionService.NewActionConfiguration NewActionConfiguration;
        
        public AddActionConfigurationRequest()
        {
        }
        
        public AddActionConfigurationRequest(Axis.Share.Soap.ActionService.NewActionConfiguration NewActionConfiguration)
        {
            this.NewActionConfiguration = NewActionConfiguration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActionConfigurationResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class AddActionConfigurationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ConfigurationID;
        
        public AddActionConfigurationResponse()
        {
        }
        
        public AddActionConfigurationResponse(string ConfigurationID)
        {
            this.ConfigurationID = ConfigurationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveActionConfiguration", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class RemoveActionConfigurationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ConfigurationID;
        
        public RemoveActionConfigurationRequest()
        {
        }
        
        public RemoveActionConfigurationRequest(string ConfigurationID)
        {
            this.ConfigurationID = ConfigurationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveActionConfigurationResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class RemoveActionConfigurationResponse
    {
        
        public RemoveActionConfigurationResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionConfiguration
    {
        
        private string configurationIDField;
        
        private string nameField;
        
        private string templateTokenField;
        
        private ActionParameters parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string ConfigurationID
        {
            get
            {
                return this.configurationIDField;
            }
            set
            {
                this.configurationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TemplateToken
        {
            get
            {
                return this.templateTokenField;
            }
            set
            {
                this.templateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ActionParameters Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionConfigurations", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetActionConfigurationsRequest
    {
        
        public GetActionConfigurationsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionConfigurationsResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetActionConfigurationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Axis.Share.Soap.ActionService.ActionConfiguration[] ActionConfigurations;
        
        public GetActionConfigurationsResponse()
        {
        }
        
        public GetActionConfigurationsResponse(Axis.Share.Soap.ActionService.ActionConfiguration[] ActionConfigurations)
        {
            this.ActionConfigurations = ActionConfigurations;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class RecipientTemplate
    {
        
        private string templateTokenField;
        
        private ActionTemplateParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TemplateToken
        {
            get
            {
                return this.templateTokenField;
            }
            set
            {
                this.templateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public ActionTemplateParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipientTemplates", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetRecipientTemplatesRequest
    {
        
        public GetRecipientTemplatesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipientTemplatesResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetRecipientTemplatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Axis.Share.Soap.ActionService.RecipientTemplate[] RecipientTemplates;
        
        public GetRecipientTemplatesResponse()
        {
        }
        
        public GetRecipientTemplatesResponse(Axis.Share.Soap.ActionService.RecipientTemplate[] RecipientTemplates)
        {
            this.RecipientTemplates = RecipientTemplates;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class NewRecipientConfiguration
    {
        
        private string nameField;
        
        private string templateTokenField;
        
        private ActionParameters parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TemplateToken
        {
            get
            {
                return this.templateTokenField;
            }
            set
            {
                this.templateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ActionParameters Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddRecipientConfiguration", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class AddRecipientConfigurationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        public Axis.Share.Soap.ActionService.NewRecipientConfiguration NewRecipientConfiguration;
        
        public AddRecipientConfigurationRequest()
        {
        }
        
        public AddRecipientConfigurationRequest(Axis.Share.Soap.ActionService.NewRecipientConfiguration NewRecipientConfiguration)
        {
            this.NewRecipientConfiguration = NewRecipientConfiguration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddRecipientConfigurationResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class AddRecipientConfigurationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ConfigurationID;
        
        public AddRecipientConfigurationResponse()
        {
        }
        
        public AddRecipientConfigurationResponse(string ConfigurationID)
        {
            this.ConfigurationID = ConfigurationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveRecipientConfiguration", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class RemoveRecipientConfigurationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ConfigurationID;
        
        public RemoveRecipientConfigurationRequest()
        {
        }
        
        public RemoveRecipientConfigurationRequest(string ConfigurationID)
        {
            this.ConfigurationID = ConfigurationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveRecipientConfigurationResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class RemoveRecipientConfigurationResponse
    {
        
        public RemoveRecipientConfigurationResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class RecipientConfiguration
    {
        
        private string configurationIDField;
        
        private string templateTokenField;
        
        private string nameField;
        
        private ActionParameters parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string ConfigurationID
        {
            get
            {
                return this.configurationIDField;
            }
            set
            {
                this.configurationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TemplateToken
        {
            get
            {
                return this.templateTokenField;
            }
            set
            {
                this.templateTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ActionParameters Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipientConfigurations", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetRecipientConfigurationsRequest
    {
        
        public GetRecipientConfigurationsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecipientConfigurationsResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetRecipientConfigurationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Axis.Share.Soap.ActionService.RecipientConfiguration[] RecipientConfigurations;
        
        public GetRecipientConfigurationsResponse()
        {
        }
        
        public GetRecipientConfigurationsResponse(Axis.Share.Soap.ActionService.RecipientConfiguration[] RecipientConfigurations)
        {
            this.RecipientConfigurations = RecipientConfigurations;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class NewActionRule
    {
        
        private string nameField;
        
        private bool enabledField;
        
        private FilterType startEventField;
        
        private FilterType[] conditionsField;
        
        private string activationTimeoutField;
        
        private string primaryActionField;
        
        private string failoverActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FilterType StartEvent
        {
            get
            {
                return this.startEventField;
            }
            set
            {
                this.startEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Condition", IsNullable=false)]
        public FilterType[] Conditions
        {
            get
            {
                return this.conditionsField;
            }
            set
            {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=4)]
        public string ActivationTimeout
        {
            get
            {
                return this.activationTimeoutField;
            }
            set
            {
                this.activationTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string PrimaryAction
        {
            get
            {
                return this.primaryActionField;
            }
            set
            {
                this.primaryActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string FailoverAction
        {
            get
            {
                return this.failoverActionField;
            }
            set
            {
                this.failoverActionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/b-2")]
    public partial class FilterType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActionRule", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class AddActionRuleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        public Axis.Share.Soap.ActionService.NewActionRule NewActionRule;
        
        public AddActionRuleRequest()
        {
        }
        
        public AddActionRuleRequest(Axis.Share.Soap.ActionService.NewActionRule NewActionRule)
        {
            this.NewActionRule = NewActionRule;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddActionRuleResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class AddActionRuleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RuleID;
        
        public AddActionRuleResponse()
        {
        }
        
        public AddActionRuleResponse(string RuleID)
        {
            this.RuleID = RuleID;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/action1")]
    public partial class ActionRule
    {
        
        private string ruleIDField;
        
        private string nameField;
        
        private bool enabledField;
        
        private FilterType startEventField;
        
        private FilterType[] conditionsField;
        
        private string activationTimeoutField;
        
        private string primaryActionField;
        
        private string failoverActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string RuleID
        {
            get
            {
                return this.ruleIDField;
            }
            set
            {
                this.ruleIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public FilterType StartEvent
        {
            get
            {
                return this.startEventField;
            }
            set
            {
                this.startEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Condition", IsNullable=false)]
        public FilterType[] Conditions
        {
            get
            {
                return this.conditionsField;
            }
            set
            {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=5)]
        public string ActivationTimeout
        {
            get
            {
                return this.activationTimeoutField;
            }
            set
            {
                this.activationTimeoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=6)]
        public string PrimaryAction
        {
            get
            {
                return this.primaryActionField;
            }
            set
            {
                this.primaryActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=7)]
        public string FailoverAction
        {
            get
            {
                return this.failoverActionField;
            }
            set
            {
                this.failoverActionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionRules", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetActionRulesRequest
    {
        
        public GetActionRulesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetActionRulesResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class GetActionRulesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Axis.Share.Soap.ActionService.ActionRule[] ActionRules;
        
        public GetActionRulesResponse()
        {
        }
        
        public GetActionRulesResponse(Axis.Share.Soap.ActionService.ActionRule[] ActionRules)
        {
            this.ActionRules = ActionRules;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveActionRule", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class RemoveActionRuleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/action1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string RuleID;
        
        public RemoveActionRuleRequest()
        {
        }
        
        public RemoveActionRuleRequest(string RuleID)
        {
            this.RuleID = RuleID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveActionRuleResponse", WrapperNamespace="http://www.axis.com/vapix/ws/action1", IsWrapped=true)]
    public partial class RemoveActionRuleResponse
    {
        
        public RemoveActionRuleResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ActionChannel : Axis.Share.Soap.ActionService.Action, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ActionClient : System.ServiceModel.ClientBase<Axis.Share.Soap.ActionService.Action>, Axis.Share.Soap.ActionService.Action
    {
        
        public ActionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionTemplatesResponse> Axis.Share.Soap.ActionService.Action.GetActionTemplatesAsync(Axis.Share.Soap.ActionService.GetActionTemplatesRequest request)
        {
            return base.Channel.GetActionTemplatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionTemplatesResponse> GetActionTemplatesAsync()
        {
            Axis.Share.Soap.ActionService.GetActionTemplatesRequest inValue = new Axis.Share.Soap.ActionService.GetActionTemplatesRequest();
            return ((Axis.Share.Soap.ActionService.Action)(this)).GetActionTemplatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddActionConfigurationResponse> Axis.Share.Soap.ActionService.Action.AddActionConfigurationAsync(Axis.Share.Soap.ActionService.AddActionConfigurationRequest request)
        {
            return base.Channel.AddActionConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddActionConfigurationResponse> AddActionConfigurationAsync(Axis.Share.Soap.ActionService.NewActionConfiguration NewActionConfiguration)
        {
            Axis.Share.Soap.ActionService.AddActionConfigurationRequest inValue = new Axis.Share.Soap.ActionService.AddActionConfigurationRequest();
            inValue.NewActionConfiguration = NewActionConfiguration;
            return ((Axis.Share.Soap.ActionService.Action)(this)).AddActionConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveActionConfigurationResponse> Axis.Share.Soap.ActionService.Action.RemoveActionConfigurationAsync(Axis.Share.Soap.ActionService.RemoveActionConfigurationRequest request)
        {
            return base.Channel.RemoveActionConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveActionConfigurationResponse> RemoveActionConfigurationAsync(string ConfigurationID)
        {
            Axis.Share.Soap.ActionService.RemoveActionConfigurationRequest inValue = new Axis.Share.Soap.ActionService.RemoveActionConfigurationRequest();
            inValue.ConfigurationID = ConfigurationID;
            return ((Axis.Share.Soap.ActionService.Action)(this)).RemoveActionConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionConfigurationsResponse> Axis.Share.Soap.ActionService.Action.GetActionConfigurationsAsync(Axis.Share.Soap.ActionService.GetActionConfigurationsRequest request)
        {
            return base.Channel.GetActionConfigurationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionConfigurationsResponse> GetActionConfigurationsAsync()
        {
            Axis.Share.Soap.ActionService.GetActionConfigurationsRequest inValue = new Axis.Share.Soap.ActionService.GetActionConfigurationsRequest();
            return ((Axis.Share.Soap.ActionService.Action)(this)).GetActionConfigurationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetRecipientTemplatesResponse> Axis.Share.Soap.ActionService.Action.GetRecipientTemplatesAsync(Axis.Share.Soap.ActionService.GetRecipientTemplatesRequest request)
        {
            return base.Channel.GetRecipientTemplatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetRecipientTemplatesResponse> GetRecipientTemplatesAsync()
        {
            Axis.Share.Soap.ActionService.GetRecipientTemplatesRequest inValue = new Axis.Share.Soap.ActionService.GetRecipientTemplatesRequest();
            return ((Axis.Share.Soap.ActionService.Action)(this)).GetRecipientTemplatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddRecipientConfigurationResponse> Axis.Share.Soap.ActionService.Action.AddRecipientConfigurationAsync(Axis.Share.Soap.ActionService.AddRecipientConfigurationRequest request)
        {
            return base.Channel.AddRecipientConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddRecipientConfigurationResponse> AddRecipientConfigurationAsync(Axis.Share.Soap.ActionService.NewRecipientConfiguration NewRecipientConfiguration)
        {
            Axis.Share.Soap.ActionService.AddRecipientConfigurationRequest inValue = new Axis.Share.Soap.ActionService.AddRecipientConfigurationRequest();
            inValue.NewRecipientConfiguration = NewRecipientConfiguration;
            return ((Axis.Share.Soap.ActionService.Action)(this)).AddRecipientConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveRecipientConfigurationResponse> Axis.Share.Soap.ActionService.Action.RemoveRecipientConfigurationAsync(Axis.Share.Soap.ActionService.RemoveRecipientConfigurationRequest request)
        {
            return base.Channel.RemoveRecipientConfigurationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveRecipientConfigurationResponse> RemoveRecipientConfigurationAsync(string ConfigurationID)
        {
            Axis.Share.Soap.ActionService.RemoveRecipientConfigurationRequest inValue = new Axis.Share.Soap.ActionService.RemoveRecipientConfigurationRequest();
            inValue.ConfigurationID = ConfigurationID;
            return ((Axis.Share.Soap.ActionService.Action)(this)).RemoveRecipientConfigurationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetRecipientConfigurationsResponse> Axis.Share.Soap.ActionService.Action.GetRecipientConfigurationsAsync(Axis.Share.Soap.ActionService.GetRecipientConfigurationsRequest request)
        {
            return base.Channel.GetRecipientConfigurationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetRecipientConfigurationsResponse> GetRecipientConfigurationsAsync()
        {
            Axis.Share.Soap.ActionService.GetRecipientConfigurationsRequest inValue = new Axis.Share.Soap.ActionService.GetRecipientConfigurationsRequest();
            return ((Axis.Share.Soap.ActionService.Action)(this)).GetRecipientConfigurationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddActionRuleResponse> Axis.Share.Soap.ActionService.Action.AddActionRuleAsync(Axis.Share.Soap.ActionService.AddActionRuleRequest request)
        {
            return base.Channel.AddActionRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.AddActionRuleResponse> AddActionRuleAsync(Axis.Share.Soap.ActionService.NewActionRule NewActionRule)
        {
            Axis.Share.Soap.ActionService.AddActionRuleRequest inValue = new Axis.Share.Soap.ActionService.AddActionRuleRequest();
            inValue.NewActionRule = NewActionRule;
            return ((Axis.Share.Soap.ActionService.Action)(this)).AddActionRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionRulesResponse> Axis.Share.Soap.ActionService.Action.GetActionRulesAsync(Axis.Share.Soap.ActionService.GetActionRulesRequest request)
        {
            return base.Channel.GetActionRulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.GetActionRulesResponse> GetActionRulesAsync()
        {
            Axis.Share.Soap.ActionService.GetActionRulesRequest inValue = new Axis.Share.Soap.ActionService.GetActionRulesRequest();
            return ((Axis.Share.Soap.ActionService.Action)(this)).GetActionRulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveActionRuleResponse> Axis.Share.Soap.ActionService.Action.RemoveActionRuleAsync(Axis.Share.Soap.ActionService.RemoveActionRuleRequest request)
        {
            return base.Channel.RemoveActionRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.ActionService.RemoveActionRuleResponse> RemoveActionRuleAsync(string RuleID)
        {
            Axis.Share.Soap.ActionService.RemoveActionRuleRequest inValue = new Axis.Share.Soap.ActionService.RemoveActionRuleRequest();
            inValue.RuleID = RuleID;
            return ((Axis.Share.Soap.ActionService.Action)(this)).RemoveActionRuleAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
