//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axis.Share.Soap.EventService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class InvalidScheduleFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class ICalendar
    {
        
        private string dialectField;
        
        private string valueField;
        
        public ICalendar()
        {
            this.dialectField = "http://www.axis.com/vapix/ws/ical1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        [System.ComponentModel.DefaultValueAttribute("http://www.axis.com/vapix/ws/ical1")]
        public string Dialect
        {
            get
            {
                return this.dialectField;
            }
            set
            {
                this.dialectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class Schedule
    {
        
        private ICalendar iCalendarField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ICalendar ICalendar
        {
            get
            {
                return this.iCalendarField;
            }
            set
            {
                this.iCalendarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class NewScheduledEvent
    {
        
        private string eventIDField;
        
        private string nameField;
        
        private Schedule scheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EventID
        {
            get
            {
                return this.eventIDField;
            }
            set
            {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Schedule Schedule
        {
            get
            {
                return this.scheduleField;
            }
            set
            {
                this.scheduleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public partial class QueryExpressionType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private string dialectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Dialect
        {
            get
            {
                return this.dialectField;
            }
            set
            {
                this.dialectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public partial class Documentation
    {
        
        private System.Xml.XmlNode[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopicSetType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopicType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TopicNamespaceType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public abstract partial class ExtensibleDocumented
    {
        
        private Documentation documentationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Documentation documentation
        {
            get
            {
                return this.documentationField;
            }
            set
            {
                this.documentationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public partial class TopicSetType : ExtensibleDocumented
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public partial class TopicType : ExtensibleDocumented
    {
        
        private QueryExpressionType messagePatternField;
        
        private TopicType[] topicField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private System.Xml.XmlQualifiedName[] messageTypesField;
        
        private bool finalField;
        
        public TopicType()
        {
            this.finalField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QueryExpressionType MessagePattern
        {
            get
            {
                return this.messagePatternField;
            }
            set
            {
                this.messagePatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Topic", Order=1)]
        public TopicType[] Topic
        {
            get
            {
                return this.topicField;
            }
            set
            {
                this.topicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Xml.XmlQualifiedName[] messageTypes
        {
            get
            {
                return this.messageTypesField;
            }
            set
            {
                this.messageTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool final
        {
            get
            {
                return this.finalField;
            }
            set
            {
                this.finalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public partial class TopicNamespaceType : ExtensibleDocumented
    {
        
        private TopicNamespaceTypeTopic[] topicField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string nameField;
        
        private string targetNamespaceField;
        
        private bool finalField;
        
        public TopicNamespaceType()
        {
            this.finalField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Topic", Order=0)]
        public TopicNamespaceTypeTopic[] Topic
        {
            get
            {
                return this.topicField;
            }
            set
            {
                this.topicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string targetNamespace
        {
            get
            {
                return this.targetNamespaceField;
            }
            set
            {
                this.targetNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool final
        {
            get
            {
                return this.finalField;
            }
            set
            {
                this.finalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wsn/t-1")]
    public partial class TopicNamespaceTypeTopic : TopicType
    {
        
        private string parentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class InvalidScheduledEventIDFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class ScheduledEventAlreadyExistsFault
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class ScheduledEventNotFoundFault
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.axis.com/vapix/ws/event1", ConfigurationName="Axis.Share.Soap.EventService.Event")]
    public interface Event
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/event1/GetEventInstances", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtensibleDocumented))]
        System.Threading.Tasks.Task<Axis.Share.Soap.EventService.GetEventInstancesResponse> GetEventInstancesAsync(Axis.Share.Soap.EventService.GetEventInstancesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/event1/AddScheduledEvent", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.EventService.InvalidScheduleFault), Action="http://www.axis.com/vapix/ws/event1/AddScheduledEvent", Name="InvalidScheduleFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.EventService.InvalidScheduledEventIDFault), Action="http://www.axis.com/vapix/ws/event1/AddScheduledEvent", Name="InvalidScheduledEventIDFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.EventService.ScheduledEventAlreadyExistsFault), Action="http://www.axis.com/vapix/ws/event1/AddScheduledEvent", Name="ScheduledEventAlreadyExistsFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtensibleDocumented))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="EventID")]
        System.Threading.Tasks.Task<string> AddScheduledEventAsync(Axis.Share.Soap.EventService.NewScheduledEvent NewScheduledEvent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/event1/RemoveScheduledEvent", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Axis.Share.Soap.EventService.ScheduledEventNotFoundFault), Action="http://www.axis.com/vapix/ws/event1/RemoveScheduledEvent", Name="ScheduledEventNotFoundFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtensibleDocumented))]
        System.Threading.Tasks.Task RemoveScheduledEventAsync(string EventID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/event1/GetScheduledEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtensibleDocumented))]
        System.Threading.Tasks.Task<Axis.Share.Soap.EventService.GetScheduledEventsResponse> GetScheduledEventsAsync(Axis.Share.Soap.EventService.GetScheduledEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.axis.com/vapix/ws/event1/ChangeVirtualInputState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExtensibleDocumented))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="stateChanged")]
        System.Threading.Tasks.Task<bool> ChangeVirtualInputStateAsync(int port, bool active);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventInstances", WrapperNamespace="http://www.axis.com/vapix/ws/event1", IsWrapped=true)]
    public partial class GetEventInstancesRequest
    {
        
        public GetEventInstancesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEventInstancesResponse", WrapperNamespace="http://www.axis.com/vapix/ws/event1", IsWrapped=true)]
    public partial class GetEventInstancesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://docs.oasis-open.org/wsn/t-1")]
        public Axis.Share.Soap.EventService.TopicSetType TopicSet;
        
        public GetEventInstancesResponse()
        {
        }
        
        public GetEventInstancesResponse(Axis.Share.Soap.EventService.TopicSetType TopicSet)
        {
            this.TopicSet = TopicSet;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class ScheduleFilter
    {
        
        private ScheduledType scheduleTypeField;
        
        private bool scheduleTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScheduledType ScheduleType
        {
            get
            {
                return this.scheduleTypeField;
            }
            set
            {
                this.scheduleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ScheduleTypeSpecified
        {
            get
            {
                return this.scheduleTypeFieldSpecified;
            }
            set
            {
                this.scheduleTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/event1")]
    public enum ScheduledType
    {
        
        /// <remarks/>
        Interval,
        
        /// <remarks/>
        Pulse,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.axis.com/vapix/ws/event1")]
    public partial class ScheduledEvent
    {
        
        private string eventIDField;
        
        private string nameField;
        
        private Schedule scheduleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EventID
        {
            get
            {
                return this.eventIDField;
            }
            set
            {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Schedule Schedule
        {
            get
            {
                return this.scheduleField;
            }
            set
            {
                this.scheduleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduledEvents", WrapperNamespace="http://www.axis.com/vapix/ws/event1", IsWrapped=true)]
    public partial class GetScheduledEventsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/event1", Order=0)]
        public Axis.Share.Soap.EventService.ScheduleFilter ScheduleFilter;
        
        public GetScheduledEventsRequest()
        {
        }
        
        public GetScheduledEventsRequest(Axis.Share.Soap.EventService.ScheduleFilter ScheduleFilter)
        {
            this.ScheduleFilter = ScheduleFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetScheduledEventsResponse", WrapperNamespace="http://www.axis.com/vapix/ws/event1", IsWrapped=true)]
    public partial class GetScheduledEventsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.axis.com/vapix/ws/event1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Axis.Share.Soap.EventService.ScheduledEvent[] ScheduledEvents;
        
        public GetScheduledEventsResponse()
        {
        }
        
        public GetScheduledEventsResponse(Axis.Share.Soap.EventService.ScheduledEvent[] ScheduledEvents)
        {
            this.ScheduledEvents = ScheduledEvents;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface EventChannel : Axis.Share.Soap.EventService.Event, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class EventClient : System.ServiceModel.ClientBase<Axis.Share.Soap.EventService.Event>, Axis.Share.Soap.EventService.Event
    {
        
        public EventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.EventService.GetEventInstancesResponse> Axis.Share.Soap.EventService.Event.GetEventInstancesAsync(Axis.Share.Soap.EventService.GetEventInstancesRequest request)
        {
            return base.Channel.GetEventInstancesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.EventService.GetEventInstancesResponse> GetEventInstancesAsync()
        {
            Axis.Share.Soap.EventService.GetEventInstancesRequest inValue = new Axis.Share.Soap.EventService.GetEventInstancesRequest();
            return ((Axis.Share.Soap.EventService.Event)(this)).GetEventInstancesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> AddScheduledEventAsync(Axis.Share.Soap.EventService.NewScheduledEvent NewScheduledEvent)
        {
            return base.Channel.AddScheduledEventAsync(NewScheduledEvent);
        }
        
        public System.Threading.Tasks.Task RemoveScheduledEventAsync(string EventID)
        {
            return base.Channel.RemoveScheduledEventAsync(EventID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Axis.Share.Soap.EventService.GetScheduledEventsResponse> Axis.Share.Soap.EventService.Event.GetScheduledEventsAsync(Axis.Share.Soap.EventService.GetScheduledEventsRequest request)
        {
            return base.Channel.GetScheduledEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Axis.Share.Soap.EventService.GetScheduledEventsResponse> GetScheduledEventsAsync(Axis.Share.Soap.EventService.ScheduleFilter ScheduleFilter)
        {
            Axis.Share.Soap.EventService.GetScheduledEventsRequest inValue = new Axis.Share.Soap.EventService.GetScheduledEventsRequest();
            inValue.ScheduleFilter = ScheduleFilter;
            return ((Axis.Share.Soap.EventService.Event)(this)).GetScheduledEventsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeVirtualInputStateAsync(int port, bool active)
        {
            return base.Channel.ChangeVirtualInputStateAsync(port, active);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
